using System.Collections.Generic;
using UnityEngine;

namespace UInput
{
    public static class InputModuleExtra
    {
        /// <summary>
        /// Unity的keycode -> VirtualKeycodes
        /// </summary>
        public static readonly Dictionary<KeyCode, VirtualKeycode> KeycodeToGlobalKeycode = new Dictionary<KeyCode, VirtualKeycode>()
        {
            //数字键
            {KeyCode.Alpha0, VirtualKeycode.Alphanumeric_0},
            {KeyCode.Alpha1, VirtualKeycode.Alphanumeric_1},
            {KeyCode.Alpha2, VirtualKeycode.Alphanumeric_2},
            {KeyCode.Alpha3, VirtualKeycode.Alphanumeric_3},
            {KeyCode.Alpha4, VirtualKeycode.Alphanumeric_4},
            {KeyCode.Alpha5, VirtualKeycode.Alphanumeric_5},
            {KeyCode.Alpha6, VirtualKeycode.Alphanumeric_6},
            {KeyCode.Alpha7, VirtualKeycode.Alphanumeric_7},
            {KeyCode.Alpha8, VirtualKeycode.Alphanumeric_8},
            {KeyCode.Alpha9, VirtualKeycode.Alphanumeric_9},
            {KeyCode.Keypad0, VirtualKeycode.Numpad_0},
            {KeyCode.Keypad1, VirtualKeycode.Numpad_1},
            {KeyCode.Keypad2, VirtualKeycode.Numpad_2},
            {KeyCode.Keypad3, VirtualKeycode.Numpad_3},
            {KeyCode.Keypad4, VirtualKeycode.Numpad_4},
            {KeyCode.Keypad5, VirtualKeycode.Numpad_5},
            {KeyCode.Keypad6, VirtualKeycode.Numpad_6},
            {KeyCode.Keypad7, VirtualKeycode.Numpad_7},
            {KeyCode.Keypad8, VirtualKeycode.Numpad_8},
            {KeyCode.Keypad9, VirtualKeycode.Numpad_9},
            //F键
            {KeyCode.F1, VirtualKeycode.F1},
            {KeyCode.F2, VirtualKeycode.F2},
            {KeyCode.F3, VirtualKeycode.F3},
            {KeyCode.F4, VirtualKeycode.F4},
            {KeyCode.F5, VirtualKeycode.F5},
            {KeyCode.F6, VirtualKeycode.F6},
            {KeyCode.F7, VirtualKeycode.F7},
            {KeyCode.F8, VirtualKeycode.F8},
            {KeyCode.F9, VirtualKeycode.F9},
            {KeyCode.F10, VirtualKeycode.F10},
            {KeyCode.F11, VirtualKeycode.F11},
            {KeyCode.F12, VirtualKeycode.F12},
            {KeyCode.F13, VirtualKeycode.F13},
            {KeyCode.F14, VirtualKeycode.F14},
            {KeyCode.F15, VirtualKeycode.F15},
            {KeyCode.Escape, VirtualKeycode.Esc},
            {KeyCode.SysReq, VirtualKeycode.PrintScreen},
            {KeyCode.ScrollLock, VirtualKeycode.ScrollLock},
            {KeyCode.Pause, VirtualKeycode.Pause},
            {KeyCode.BackQuote, VirtualKeycode.OEM_3},
            {KeyCode.Minus, VirtualKeycode.OEM_Minus},
            {KeyCode.Equals, VirtualKeycode.OEM_Plus},
            {KeyCode.Backspace, VirtualKeycode.Backspace},
            {KeyCode.Insert, VirtualKeycode.Insert},
            {KeyCode.Home, VirtualKeycode.Home},
            {KeyCode.PageUp, VirtualKeycode.PageUp},
            {KeyCode.Numlock, VirtualKeycode.Numlock},
            {KeyCode.KeypadDivide, VirtualKeycode.Divide},
            {KeyCode.KeypadMinus, VirtualKeycode.Subtract},
            {KeyCode.KeypadPlus, VirtualKeycode.Add},
            {KeyCode.KeypadEnter, VirtualKeycode.Enter},
            {KeyCode.KeypadPeriod, VirtualKeycode.Decimal},
            {KeyCode.Tab, VirtualKeycode.Tab},
            {KeyCode.LeftBracket, VirtualKeycode.OEM_4},
            {KeyCode.RightBracket, VirtualKeycode.OEM_6},
            {KeyCode.Backslash, VirtualKeycode.OEM_5},
            {KeyCode.Delete, VirtualKeycode.Delete},
            {KeyCode.End, VirtualKeycode.End},
            {KeyCode.PageDown, VirtualKeycode.PageDown},
            {KeyCode.CapsLock, VirtualKeycode.Capslock},
            {KeyCode.Semicolon, VirtualKeycode.OEM_1},
            {KeyCode.Quote, VirtualKeycode.OEM_7},
            {KeyCode.Return, VirtualKeycode.Enter},
            {KeyCode.LeftShift, VirtualKeycode.LeftShift},
            {KeyCode.Comma, VirtualKeycode.OEM_Comma},
            {KeyCode.Period, VirtualKeycode.OEM_Period},
            {KeyCode.Slash, VirtualKeycode.OEM_2},
            {KeyCode.RightShift, VirtualKeycode.RightShift},
            {KeyCode.LeftControl, VirtualKeycode.LeftCtrl},
            {KeyCode.LeftCommand, VirtualKeycode.LeftWin},
            {KeyCode.LeftAlt, VirtualKeycode.LeftAlt},
            {KeyCode.RightAlt, VirtualKeycode.RightAlt},
            {KeyCode.Space, VirtualKeycode.Space},
            {KeyCode.Menu, VirtualKeycode.Apps},
            {KeyCode.RightControl, VirtualKeycode.RightCtrl},
            {KeyCode.UpArrow, VirtualKeycode.UpArrow},
            {KeyCode.DownArrow, VirtualKeycode.DownArrow},
            {KeyCode.LeftArrow, VirtualKeycode.LeftArrow},
            {KeyCode.RightArrow, VirtualKeycode.RightArrow},
            {KeyCode.A, VirtualKeycode.A},
            {KeyCode.B, VirtualKeycode.B},
            {KeyCode.C, VirtualKeycode.C},
            {KeyCode.D, VirtualKeycode.D},
            {KeyCode.E, VirtualKeycode.E},
            {KeyCode.F, VirtualKeycode.F},
            {KeyCode.G, VirtualKeycode.G},
            {KeyCode.H, VirtualKeycode.H},
            {KeyCode.I, VirtualKeycode.I},
            {KeyCode.J, VirtualKeycode.J},
            {KeyCode.K, VirtualKeycode.K},
            {KeyCode.L, VirtualKeycode.L},
            {KeyCode.M, VirtualKeycode.M},
            {KeyCode.N, VirtualKeycode.N},
            {KeyCode.O, VirtualKeycode.O},
            {KeyCode.P, VirtualKeycode.P},
            {KeyCode.Q, VirtualKeycode.Q},
            {KeyCode.R, VirtualKeycode.R},
            {KeyCode.S, VirtualKeycode.S},
            {KeyCode.T, VirtualKeycode.T},
            {KeyCode.U, VirtualKeycode.U},
            {KeyCode.V, VirtualKeycode.V},
            {KeyCode.W, VirtualKeycode.W},
            {KeyCode.X, VirtualKeycode.X},
            {KeyCode.Y, VirtualKeycode.Y},
            {KeyCode.Z, VirtualKeycode.Z},
            // {KeyCode.LeftApple,GlobalKeycodes.LeftWin},
            // {KeyCode.RightApple,GlobalKeycodes.RightWin},
            // {KeyCode.LeftWindows,GlobalKeycodes.LeftWin},
            // {KeyCode.RightWindows,GlobalKeycodes.RightWin},
        };      

       
    }
}